module Mask = Precalculated_mask

include Precalculated_piece
include Precalculated_castle
include Precalculated_between
include Precalculated_line
include Precalculated_mvv_lva
include Precalculated_king_area
include Precalculated_passed_pawns
include Precalculated_forward_ranks
include Precalculated_forward_files
include Precalculated_outpost_ranks
include Precalculated_outpost_squares
include Precalculated_connected_pawns
include Precalculated_king_pawn_file_distance
